//PRODUCT FUNCTONS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const LIST_PRODUCT = 'LIST_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';

//CATEGORY FUNCTIONS
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const LIST_CATEGORY = 'LIST_CATEGORY';



export const ADD_USER= 'ADD_USER';